language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x mvnw

notifications:
  email:
    recipients:
      - truezure@gmail.com 
script:
 - echo "skipping tests"