package kr.co.dwebss.kococo.api.entities;
// Generated 2019. 5. 23 ���� 7:09:58 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Analysis generated by hbm2java
 */
@Entity
@Table(name = "analysis", catalog = "kococo")
public class Analysis implements java.io.Serializable {

	private Integer analysisId;
	private Record record;
	private Date analysisStartD;
	private Date analysisStartDt;
	private Date analysisEndD;
	private Date analysisEndDt;
	private String analysisFileNm;
	private String analysisFileAppPath;
	private Character analysisServerUploadYn;
	private String analysisServerUploadPath;
	private Date analysisServerUploadDt;
	private Character claimYn;
	private Integer claimReasonCd;
	private String claimContents;
	private Date claimRegistDt;
	private Set<AnalysisDetails> analysisDetailses = new HashSet<AnalysisDetails>(0);

	public Analysis() {
	}

	public Analysis(Record record, Date analysisStartD, Date analysisStartDt, Date analysisEndD, Date analysisEndDt,
			String analysisFileNm, String analysisFileAppPath, Character analysisServerUploadYn,
			String analysisServerUploadPath, Date analysisServerUploadDt, Character claimYn, Integer claimReasonCd,
			String claimContents, Date claimRegistDt, Set<AnalysisDetails> analysisDetailses) {
		this.record = record;
		this.analysisStartD = analysisStartD;
		this.analysisStartDt = analysisStartDt;
		this.analysisEndD = analysisEndD;
		this.analysisEndDt = analysisEndDt;
		this.analysisFileNm = analysisFileNm;
		this.analysisFileAppPath = analysisFileAppPath;
		this.analysisServerUploadYn = analysisServerUploadYn;
		this.analysisServerUploadPath = analysisServerUploadPath;
		this.analysisServerUploadDt = analysisServerUploadDt;
		this.claimYn = claimYn;
		this.claimReasonCd = claimReasonCd;
		this.claimContents = claimContents;
		this.claimRegistDt = claimRegistDt;
		this.analysisDetailses = analysisDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ANALYSIS_ID", unique = true, nullable = false)
	public Integer getAnalysisId() {
		return this.analysisId;
	}

	public void setAnalysisId(Integer analysisId) {
		this.analysisId = analysisId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RECORD_ID")
	public Record getRecord() {
		return this.record;
	}

	public void setRecord(Record record) {
		this.record = record;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ANALYSIS_START_D", length = 10)
	public Date getAnalysisStartD() {
		return this.analysisStartD;
	}

	public void setAnalysisStartD(Date analysisStartD) {
		this.analysisStartD = analysisStartD;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ANALYSIS_START_DT", length = 19)
	public Date getAnalysisStartDt() {
		return this.analysisStartDt;
	}

	public void setAnalysisStartDt(Date analysisStartDt) {
		this.analysisStartDt = analysisStartDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ANALYSIS_END_D", length = 10)
	public Date getAnalysisEndD() {
		return this.analysisEndD;
	}

	public void setAnalysisEndD(Date analysisEndD) {
		this.analysisEndD = analysisEndD;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ANALYSIS_END_DT", length = 19)
	public Date getAnalysisEndDt() {
		return this.analysisEndDt;
	}

	public void setAnalysisEndDt(Date analysisEndDt) {
		this.analysisEndDt = analysisEndDt;
	}

	@Column(name = "ANALYSIS_FILE_NM", length = 30)
	public String getAnalysisFileNm() {
		return this.analysisFileNm;
	}

	public void setAnalysisFileNm(String analysisFileNm) {
		this.analysisFileNm = analysisFileNm;
	}

	@Column(name = "ANALYSIS_FILE_APP_PATH")
	public String getAnalysisFileAppPath() {
		return this.analysisFileAppPath;
	}

	public void setAnalysisFileAppPath(String analysisFileAppPath) {
		this.analysisFileAppPath = analysisFileAppPath;
	}

	@Column(name = "ANALYSIS_SERVER_UPLOAD_YN", length = 1)
	public Character getAnalysisServerUploadYn() {
		return this.analysisServerUploadYn;
	}

	public void setAnalysisServerUploadYn(Character analysisServerUploadYn) {
		this.analysisServerUploadYn = analysisServerUploadYn;
	}

	@Column(name = "ANALYSIS_SERVER_UPLOAD_PATH")
	public String getAnalysisServerUploadPath() {
		return this.analysisServerUploadPath;
	}

	public void setAnalysisServerUploadPath(String analysisServerUploadPath) {
		this.analysisServerUploadPath = analysisServerUploadPath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ANALYSIS_SERVER_UPLOAD_DT", length = 19)
	public Date getAnalysisServerUploadDt() {
		return this.analysisServerUploadDt;
	}

	public void setAnalysisServerUploadDt(Date analysisServerUploadDt) {
		this.analysisServerUploadDt = analysisServerUploadDt;
	}

	@Column(name = "CLAIM_YN", length = 1)
	public Character getClaimYn() {
		return this.claimYn;
	}

	public void setClaimYn(Character claimYn) {
		this.claimYn = claimYn;
	}

	@Column(name = "CLAIM_REASON_CD")
	public Integer getClaimReasonCd() {
		return this.claimReasonCd;
	}

	public void setClaimReasonCd(Integer claimReasonCd) {
		this.claimReasonCd = claimReasonCd;
	}

	@Column(name = "CLAIM_CONTENTS", length = 250)
	public String getClaimContents() {
		return this.claimContents;
	}

	public void setClaimContents(String claimContents) {
		this.claimContents = claimContents;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CLAIM_REGIST_DT", length = 19)
	public Date getClaimRegistDt() {
		return this.claimRegistDt;
	}

	public void setClaimRegistDt(Date claimRegistDt) {
		this.claimRegistDt = claimRegistDt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "analysis")
	public Set<AnalysisDetails> getAnalysisDetailses() {
		return this.analysisDetailses;
	}

	public void setAnalysisDetailses(Set<AnalysisDetails> analysisDetailses) {
		this.analysisDetailses = analysisDetailses;
	}

}
