package kr.co.dwebss.kococo.api.entities;
// Generated 2019. 5. 23 ���� 7:09:58 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.hateoas.ResourceSupport;

/**
 * Code generated by hbm2java
 */
@Entity
@Table(name = "code", catalog = "kococo")
public class Code extends ResourceSupport implements java.io.Serializable {

	private int code;
	private String codeCateogry;
	private String codeValue;

	public Code() {
	}

	public Code(int code) {
		this.code = code;
	}

	public Code(int code, String codeCateogry, String codeValue) {
		this.code = code;
		this.codeCateogry = codeCateogry;
		this.codeValue = codeValue;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@Column(name = "CODE_CATEOGRY", length = 10)
	public String getCodeCateogry() {
		return this.codeCateogry;
	}

	public void setCodeCateogry(String codeCateogry) {
		this.codeCateogry = codeCateogry;
	}

	@Column(name = "CODE_VALUE", length = 10)
	public String getCodeValue() {
		return this.codeValue;
	}

	public void setCodeValue(String codeValue) {
		this.codeValue = codeValue;
	}

}
